# Плагин kRTP разработан vk.com/yacushev
# Версия 2.2
# *Продажа/слив/передача запрещена!
RTP:
 # Сколько будет отниматься голода при телепортации(если не нужно, то ставить 0)
 FoodLevel: 6
Messages:
 teleport: '&aВы успешно телепортированы'
 nofood: '&aУ вас недостаточно голода, поешьте!'
 noplayer: '&cПоблизости нет игроков!'
 noPermission: '&cУ вас нет прав!'
 OnlyPlayer: '&cКоманду можно выполнять только от имени игрока!'